- hosts: all
  gather_facts: false
  vars:
    module_path: "{{lookup('config', 'DEFAULT_MODULE_PATH')}}"
  tasks:
    - name: get config
      debug: var=module-path

    - name: test paths
      stat: path={{item}}
      loop: "{{ module_path.split(':') }}"

    - name: actual test
      action: module=bcsping
