- hosts: all
  gather_facts: false
  vars:
    module_path: "{{lookup('config', 'DEFAULT_MODULE_PATH')}}"
  tasks:
    - name: debug info for test
      run_once: true
      tags: ['never', 'debug']
      block:
        - name: get config
          debug: var=module_path

        - name: test paths
          stat: path={{item}}
          loop: "{{ module_path }}"

        - name: find contents
          find: paths={{item}} recurse=yes patterns='*'
          register: found
          loop: "{{ module_path }}"

        - debug: var=found

    - name: test no namespace, changed feature so now this will use built in
      ping: data=bcspong

#    - name: test colleciton namespace, removed this 'feature'
#      bcsping.ping: data=bcspong

    - name: with full namespace
      bcs.bcsping.ping: data=pongbcs
