- hosts: all
  gather_facts: false
  vars:
    module_path: "{{lookup('config', 'DEFAULT_MODULE_PATH')}}"
  tasks:
    - name: debug info for test
      run_once: true
      tags: ['debug']
      block:
        - name: get config
          debug: var=module_path

        - name: test paths
          stat: path={{item}}
          loop: "{{ module_path }}"

        - name: find contents
          find: paths={{item}} recurse=yes patterns='*'
          register: found
          loop: "{{ module_path }}"

        - debug: var=found

    - name: actual test
      action: bcsping
